{
  "comments": [
    {
      "key": {
        "uuid": "24a1fe15_d7d45456",
        "filename": "zvmsdk/database.py",
        "patchSetId": 1
      },
      "lineNbr": 606,
      "author": {
        "id": 1008712
      },
      "writtenOn": "2017-12-27T04:42:47Z",
      "side": 0,
      "message": "you didn\u0027t consider imagename \u003d None case\nor it will be \n\nImage with name: None \n\nwhich is confusing",
      "range": {
        "startLine": 606,
        "startChar": 12,
        "endLine": 606,
        "endChar": 56
      },
      "revId": "1e997460ded0126cdc933e4ac09fceb6ca800187",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}