{
  "comments": [
    {
      "key": {
        "uuid": "3e5dae64_50be7c52",
        "filename": "zvmsdk/exception.py",
        "patchSetId": 1
      },
      "lineNbr": 233,
      "author": {
        "id": 1008712
      },
      "writtenOn": "2017-09-13T21:10:06Z",
      "side": 1,
      "message": "I have no idea why we name this ....Client caused internal error?",
      "range": {
        "startLine": 233,
        "startChar": 6,
        "endLine": 233,
        "endChar": 28
      },
      "revId": "fccefe3df334c80fa42b37df3448bc35482e959f",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "00990cbf_229b17b2",
        "filename": "zvmsdk/exception.py",
        "patchSetId": 1
      },
      "lineNbr": 233,
      "author": {
        "id": 1008926
      },
      "writtenOn": "2017-09-14T02:12:52Z",
      "side": 1,
      "message": "This is named as this when we unified the xcatinternalerror and smutinternalerror. \nsmutinternalerror means all the syntax error happen in smut, ideally in current error handling framework we don\u0027t have the need to catch such syntax error. so we have been considering removing this clientinternal error, but many places in current code uses this exception and leave it does not much harm, so I have not start this work.",
      "parentUuid": "3e5dae64_50be7c52",
      "range": {
        "startLine": 233,
        "startChar": 6,
        "endLine": 233,
        "endChar": 28
      },
      "revId": "fccefe3df334c80fa42b37df3448bc35482e959f",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "18e115a4_c609e52a",
        "filename": "zvmsdk/exception.py",
        "patchSetId": 1
      },
      "lineNbr": 233,
      "author": {
        "id": 1008712
      },
      "writtenOn": "2017-09-14T15:14:31Z",
      "side": 1,
      "message": "ok, good to know , just we can clean it up later",
      "parentUuid": "00990cbf_229b17b2",
      "range": {
        "startLine": 233,
        "startChar": 6,
        "endLine": 233,
        "endChar": 28
      },
      "revId": "fccefe3df334c80fa42b37df3448bc35482e959f",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "52ea8901_874c77e3",
        "filename": "zvmsdk/smutclient.py",
        "patchSetId": 1
      },
      "lineNbr": 60,
      "author": {
        "id": 1008953
      },
      "writtenOn": "2017-09-13T08:39:24Z",
      "side": 1,
      "message": "_is_smut_internal_error",
      "range": {
        "startLine": 60,
        "startChar": 12,
        "endLine": 60,
        "endChar": 32
      },
      "revId": "fccefe3df334c80fa42b37df3448bc35482e959f",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "da447da6_566689eb",
        "filename": "zvmsdk/smutclient.py",
        "patchSetId": 1
      },
      "lineNbr": 60,
      "author": {
        "id": 1008926
      },
      "writtenOn": "2017-09-14T02:12:52Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "52ea8901_874c77e3",
      "range": {
        "startLine": 60,
        "startChar": 12,
        "endLine": 60,
        "endChar": 32
      },
      "revId": "fccefe3df334c80fa42b37df3448bc35482e959f",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "4980e16c_412d8000",
        "filename": "zvmsdk/smutclient.py",
        "patchSetId": 1
      },
      "lineNbr": 69,
      "author": {
        "id": 1008953
      },
      "writtenOn": "2017-09-13T08:39:24Z",
      "side": 1,
      "message": "error[2] is a list of reason codes, results[\u0027rs\u0027] not in error[2]?",
      "range": {
        "startLine": 69,
        "startChar": 61,
        "endLine": 69,
        "endChar": 69
      },
      "revId": "fccefe3df334c80fa42b37df3448bc35482e959f",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "17edb327_5cf35a11",
        "filename": "zvmsdk/smutclient.py",
        "patchSetId": 1
      },
      "lineNbr": 69,
      "author": {
        "id": 1008926
      },
      "writtenOn": "2017-09-14T02:12:52Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "4980e16c_412d8000",
      "range": {
        "startLine": 69,
        "startChar": 61,
        "endLine": 69,
        "endChar": 69
      },
      "revId": "fccefe3df334c80fa42b37df3448bc35482e959f",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}